In [89]:
"""train1=read.csv("train_hr100.csv")
test1=read.csv("test_hr100.csv")
model1= rpart(job_change ~ ., train1,  method = "class")
pred1 <- predict(model1, test1, type = "class")
table(test1$left, pred1)
fancyRpartPlot(model1)"""



'train1=read.csv("train_hr100.csv")\ntest1=read.csv("test_hr100.csv")\nmodel1= rpart(job_change ~ ., train1,  method = "class")\npred1 <- predict(model1, test1, type = "class")\ntable(test1$left, pred1)\nfancyRpartPlot(model1)'

In [3]:
import pandas as pd

#Read the data 
df = pd.read_csv('/Users/harsha/Desktop/dt.csv')

from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
#encode sales
df["sales_code"] = lb_make.fit_transform(df["sales"])
df[["sales", "sales_code"]].head()


sales  sales_code
0    support           8
1  marketing           5
2    support           8
3         hr           3
4  technical           9

In [4]:
#encode salary 
df["salary_code"] = lb_make.fit_transform(df["salary"])
df[["salary", "salary_code"]].head()
df1=df.drop('sales', axis=1)
df2=df1.drop('salary', axis=1)
df2.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.98             0.53               4                   166   
1                0.48             0.51               3                   136   
2                0.84             0.50               3                   227   
3                0.73             0.98               3                   227   
4                0.10             0.92               6                   258   

   time_spend_company  Work_accident  job_change  promotion_last_5years  \
0                   2              0           0                      0   
1                   3              0           0                      0   
2                   2              0           0                      0   
3                   2              1           0                      0   
4                   4              0           1                      0   

   sales_code  salary_code  
0           8            2  
1           5            1  
2           8            1  
3           3            0  
4           9            1

In [5]:
#EDA
x=df.print(classification_report(y_test,predictions))['satisfaction_level']
ax = sns.distplot(x)

SyntaxError: invalid syntax (<ipython-input-5-425afafa0de5>, line 2)

In [6]:
from sklearn.model_selection import train_test_split

X = df2.drop('job_change',axis=1)
y = df2['job_change']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)


In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
dtree = DecisionTreeClassifier()

In [10]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
#predict on sample data

test=X[4:5]
predictions = dtree.predict(test)
predictions

array([1])

In [12]:
from sklearn.metrics import classification_report,confusion_matrix

In [13]:
print classification_report(y_test,predictions)

             precision    recall  f1-score   support

          0       0.99      0.98      0.98      2397
          1       0.94      0.95      0.95       753

avg / total       0.97      0.97      0.97      3150



In [14]:
print(confusion_matrix(y_test,predictions))

[[2349   48]
 [  34  719]]


In [17]:
from IPython.display import Image  
from sklearn.externals.six import StringIO  
from sklearn.tree import export_graphviz
import pydot 

features = df2.drop('job_change',axis=1)
features

satisfaction_level  last_evaluation  number_project  \
0                    0.98             0.53               4   
1                    0.48             0.51               3   
2                    0.84             0.50               3   
3                    0.73             0.98               3   
4                    0.10             0.92               6   
5                    0.40             0.52               2   
6                    0.09             0.82               6   
7                    0.58             0.79               5   
8                    0.58             1.00               4   
9                    0.21             0.99               6   
10                   0.30             0.67               3   
11                   0.10             0.81               7   
12                   0.98             0.54               4   
13                   0.66             0.53               4   
14                   0.70             0.60               3   
15                   0.55             0.96               4   
16                   0.90             0.97               4   
17                   0.57             0.61               5   
18                   0.60             0.76               5   
19                   0.58             0.97               3   
20                   0.18             0.64               6   
21                   0.49             0.57               3   
22                   0.50             0.40               3   
23                   0.63             0.59               4   
24                   0.54             0.97               4   
25                   0.79             0.89               5   
26                   0.89             0.71               4   
27                   0.50             0.48               4   
28                   0.75             0.89               6   
29                   0.95             0.90               4   
...                   ...              ...             ...   
10469                0.78             0.62               4   
10470                0.15             0.89               3   
10471                0.84             0.84               3   
10472                0.50             0.92               4   
10473                0.17             0.52               4   
10474                0.81             0.85               3   
10475                0.53             0.82               3   
10476                0.69             0.66               3   
10477                0.80             0.97               4   
10478                0.50             0.54               5   
10479                0.69             0.76               3   
10480                0.62             0.75               4   
10481                0.74             0.53               5   
10482                0.84             0.75               3   
10483                0.58             0.91               4   
10484                0.71             0.75               4   
10485                0.53             0.88               3   
10486                0.91             0.89               2   
10487                0.48             0.89               3   
10488                0.51             0.80               4   
10489                0.64             0.88               3   
10490                0.71             0.59               5   
10491                0.39             0.48               2   
10492                0.55             0.60               4   
10493                0.91             0.89               4   
10494                0.09             0.84               6   
10495                0.82             0.69               3   
10496                0.46             0.57               2   
10497                0.81             1.00               4   
10498                0.74             0.92               4   

       average_montly_hours  time_spend_company  Work_accident  \
0                       166                   2              0   
1                       136   

In [18]:
dot_data = StringIO()  
export_graphviz(dtree, out_file=dot_data,feature_names=features,filled=True,rounded=True)

graph = pydot.graph_from_dot_data(dot_data.getvalue())  
Image(graph[0].create_png())  

ValueError: Length of feature_names, 10499 does not match number of features, 9

In [19]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
rfc_pred = rfc.predict(X_test)
print confusion_matrix(y_test,rfc_pred)

[[2391    6]
 [  31  722]]


In [32]:
print classification_report(y_test,rfc_pred)

             precision    recall  f1-score   support

          0       0.99      1.00      0.99      2397
          1       0.99      0.96      0.98       753

avg / total       0.99      0.99      0.99      3150

